package com.example.a41845.day02_zuoye2.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a41845.day02_zuoye2.bean;

import com.example.a41845.day02_zuoye2.dao.beanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanDaoConfig;

    private final beanDao beanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanDaoConfig = daoConfigMap.get(beanDao.class).clone();
        beanDaoConfig.initIdentityScope(type);

        beanDao = new beanDao(beanDaoConfig, this);

        registerDao(bean.class, beanDao);
    }
    
    public void clear() {
        beanDaoConfig.clearIdentityScope();
    }

    public beanDao getBeanDao() {
        return beanDao;
    }

}
